### ISSUE TITLE
Printer options that is not key=value pair

### ISSUE THREAD

**Issue by heliocola** [nehresma/cupsffi#20]
Hello there,
I've been using CUPS in a project and I am running into a few issues that couldn't figure it out yet.
How can I send the option '-o landscape' to the printer using the 'print_file' method?

In the documentation it only refers to examples that are key, value pairs ({'InputSlot' => 'Upper', 'PageSize' => 'A4'}).

I tried many different ways but I always get an error.
I know the printer supports it because my files prints correctly when I use 'lpr' command line.

Thanks,
Helio

**Comment by j-mcnally** [comment]
I am also trying to figure out landscape :(

**Comment by j-mcnally** [comment]
see #22 the value for landscape is "yes" but the key is probably blocked, you need to manually whitelist it.

**Comment by nehresma** [comment]
Closing, thanks to #22 from Justin.
